CREATE TABLE IF NOT EXISTS EXCHANGE_RATE_CACHE_RECORD (
    ID              SERIAL    PRIMARY KEY,
    DAY             DATE      NOT NULL,
    BASE_CURRENCY   CHAR(3)   NOT NULL,
    CURRENCY        CHAR(3)   NOT NULL,
    RATE            DECIMAL   NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS EXCHANGE_RATE_CACHE_RECORD_UQ1 ON EXCHANGE_RATE_CACHE_RECORD (DAY, BASE_CURRENCY, CURRENCY);
